# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'attendance' do
	pod 'DBAlertController'
	pod 'Alamofire', '~> 3.0'
	pod 'SwiftValidator', '3.0.1'
end

target 'attendanceTests' do

end

target 'attendanceUITests' do

end

