# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'attendance' do
	pod 'DBAlertController'
	pod 'Alamofire', '~> 3.0'
	pod 'SwiftValidator', '3.0.1'
	pod 'SwiftyJSON', '~> 2.3'
	pod 'ActionSheetPicker-3.0'
	pod 'SwiftCharts', '~> 0.3'
	pod 'ANLongTapButton'
	pod 'XCGLogger', '~> 3.1'
	pod "PKHUD"
end

target 'attendanceTests' do

end

target 'attendanceUITests' do

end

